parameters:
- name: DATA_CONFIG_PATH
  type: string
- name: DATA_PURPOSE
  type: string
- name: ENVIRONMENT_NAME
  type: string
- name: BATCH_DEPLOYMENT_CONFIG
  type: string

steps:
- template: register_data_asset.yml
  parameters:
    step_name: "register batch test data"
    script_parameter: |
      python -m mlops.common.register_data_asset \
        --data_purpose ${{ parameters.DATA_PURPOSE }} \
        --data_config_path ${{ parameters.DATA_CONFIG_PATH }} \
        --environment_name ${{ parameters.ENVIRONMENT_NAME }}

- template: execute_python_code.yml
  parameters:
    step_name: "test azureml batch endpoint"
    script_parameter: |
      python -m mlops.common.deployment.run_test_batch_deployment \
        --data_purpose ${{ parameters.DATA_PURPOSE }} \
        --data_config_path ${{ parameters.DATA_CONFIG_PATH }} \
        --environment_name ${{ parameters.ENVIRONMENT_NAME }} \
        --batch_config ${{ parameters.BATCH_DEPLOYMENT_CONFIG }}
