pr: none
trigger: none
pool:
  vmImage: ubuntu-latest


# variables:
# - group: mlops_platform_dev_vg

# parameters:
#  - name: env_name
#    displayName: "Execution Environment"
#    default: "infra"

stages:
  - stage: DevInfraProvision
    displayName: 'Dev-Infra Provision'
    variables:
      - group: mlops_platform_infra_dev_vg
    jobs:
      - template: ../../templates/platform_infra_bicep_pipeline.yml
        parameters:
          variableGroup: '${{variables.group}}'
          
  - stage: TestInfraProvision
    displayName: 'Test-Infra Provision'
    variables:
      - group: mlops_platform_infra_test_vg
    jobs:
      - template: ../../templates/platform_infra_bicep_pipeline.yml
        parameters:
          variableGroup: '${{variables.group}}'