pr: none
trigger: none
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_infra_dev_vg

jobs:
    - job: Publish_IaC_Templates
      steps:
          - checkout: self
            clean: true
          - task: CopyFiles@2
            displayName: 'Copy templates'
            inputs:
              sourceFolder: '$(Pipeline.Workspace)/s'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
            enabled: false

          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: infratemplates 
            enabled: false

    - job: Deploy_MLOps_v2_Infrastructure 
      steps:
      - download: current
        artifact: infratemplates
        displayName: Download IaC Templates

      - script: |
          echo 'See the contents of parameters passed in'
          echo '$(AZURE_RM_SVC_CONNECTION)'
          echo '$(BICEP_RESOURCE_GROUP_NAME)'
          echo '$(LOCATION)'
          echo '$(STORAGE_ACCT_NAME)'
          echo '$(KEYVAULT_NAME)'
          echo '$(APPINSIGHTS_NAME)'
          echo '$(CONTAINER_REGISTRY_NAME)'
          echo '$(WORKSPACE_NAME)'
        enabled: true

      - task: AzureCLI@2
        displayName: Provision AzureML Infrastructure
        inputs:
          azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
          scriptType: pscore
          scriptLocation: inlineScript
          useGlobalConfig: false
          inlineScript: |
            az --version
            az deployment sub create --location='$(LOCATION)' `
            --template-file '$(Pipeline.Workspace)/infratemplates/infra/bicep/public_workspace/main.bicep' `
            --parameters resourceGroupName='$(RESOURCE_GROUP_NAME)' location='$(LOCATION)' `
            storageAccount='$(STORAGE_ACCT_NAME)' `
            keyVaultName='$(KEYVAULT_NAME)' `
            appInsightsName='$(APPINSIGHTS_NAME)' `
            containerRegistryName='$(CONTAINER_REGISTRY_NAME)' `
            amlWorkspaceName='$(WORKSPACE_NAME)'
        enabled: true                