pr: none
trigger: none
pool:
  vmImage: ubuntu-latest


# variables:
# - group: mlops_platform_dev_vg

# parameters:
#  - name: env_name
#    displayName: "Execution Environment"
#    default: "infra"

stages:
    - stage: Dev-InfraProvision
      jobs:
        - job: InfraProvision
          displayName: 'Dev-Infra Provision'
          variables:
            - group: mlops_platform_dev_vg
          steps:
            - template: ../../templates/platform_infra_bicep_pipeline.yml

      # env_name: ${{parameters.env_name}}

    # parameters:
    #   environmentName: $(ENVIRONMENT)
    #   azureMgrConnection: $(AZURE_RM_SVC_CONNECTION)
    #   resourceGroup: $(RESOURCE_GROUP_NAME)
    #   location: $(LOCATION)
    #   storageAccount: $(STORAGEACCOUNT)
    #   keyVaultName: $(KEYVAULT_NAME)
    #   appInsightsName: $(APPINSIGHTS)
    #   containerRegistryName: $(REGISTRY_NAME)
    #   amlWorkspaceName: $(WORKSPACE_NAME)
    #   clusterName: $(CLUSTER_NAME)
    #   clusterSize: $(CLUSTER_SIZE)
    #   batchClusterName: $(BATCH_CLUSTER_NAME)

