jobs:
- job: BuildJob
  displayName: Build Job
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        Dockerfile: mlops/custom_objectdetection/environment/Dockerfile
        tags: |
          $(Build.Repository.Name):$(Build.BuildId)

- job: Build_Validation_Pipeline
  displayName: Build Validation Pipeline
  dependsOn: BuildJob
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: Docker@2
      displayName: Run Docker container for validation
      inputs:
        command: run
        imageName: $(Build.Repository.Name):$(Build.BuildId)
        containerName: validation_container
        options: '--rm'
        arguments: >
          /bin/bash -c "
          python -m pip install --upgrade pip &&
          pip install -r .azure-pipelines/requirements/build_validation_requirements.txt &&
          flake8 . &&
          pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml
          "

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish Test Results for Python $(python.version)'