parameters:
  - name: image_name
    displayName: "Name of the Docker image"
  - name: model_type
    displayName: "Model Type"

jobs:
- job: BuildJob
  displayName: Build Job
  pool:
    vmImage: ubuntu-latest
  steps:
    - script: |
        python -m pip install --upgrade pip &&
        pip install -r .azure-pipelines/requirements/build_validation_requirements.txt &&
        flake8 .
      displayName: 'Install dependencies and run linting'

    # TODO: this won't work for non dockerfile pipelines
    - script: | 
        echo "Building Docker container for validation with tag: ${{ parameters.image_name }}"
        docker build -t ${{ parameters.image_name }} -f mlops/${{ parameters.model_type }}/environment/Dockerfile mlops/${{ parameters.model_type }}/environment
      displayName: 'Build Docker container'

    - script: |
        echo "Running Docker container~ for validation"
        docker run --rm --mount type=bind,src=.,dst=/workspace ${{ parameters.image_name }} /bin/bash -c "
          pwd &&
          sudo chown -R vscode /workspace &&
          python -m pip install --upgrade pip &&
          pip install -r .azure-pipelines/requirements/build_validation_requirements.txt &&
          python -m pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml
        "
      displayName: 'Run tests in Docker container'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish Test Results for Python $(python.version)'