parameters:
  - name: azure_subscription
    type: string
  - name: resource_group_name
    type: string
  - name: workspace_name
    type: string
  - name: run_name
    type: string

steps:
  - task: AzureCLI@2
    displayName: "Cancel AML Pipeline"
    inputs:
      azureSubscription: ${{ parameters.azure_subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Pipeline was canceled. Attempting to cancel AML Pipeline..."
        echo "Job name to cancel: ${{ parameters.run_name }}"

        az extension add --name ml
        az ml job cancel --name ${{ parameters.run_name }} \
          --resource-group ${{ parameters.resource_group_name }} \
          --workspace-name ${{ parameters.workspace_name }}
