parameters:
- name: MODEL_TYPE
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: RUN_ID
  type: string

stages:
- stage: 'Deploy_Online'
  displayName: 'Deploy as Online Endpoint'
  condition: variables['IS_ONLINE_DEPLOYMENT']
  jobs:
  - job: Execute_Deployment_Job
    steps:
    - template: configure_azureml_agent.yml
    - template: execute_python_code.yml
      parameters:
        step_name: "provision azureml online endpoint"
        script_parameter: |
          python -m mlops.common.deployment.provision_online_endpoint \
            --run_id ${{ parameters.RUN_ID }} \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}

    - template: execute_python_code.yml
      parameters:
        step_name: "provision azureml deployment"
        script_parameter: |
          python -m mlops.common.deployment.provision_online_deployment \
            --run_id ${{ parameters.RUN_ID }} \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}

    - template: execute_python_code.yml
      parameters:
        step_name: "test azureml real endpoint"
        script_parameter: |
          python -m mlops.common.deployment.run_test_model_on_aml \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}

- stage: 'Deploy_Batch'
  displayName: 'Deploy as Batch Endpoint'
  condition: variables['IS_BATCH_DEPLOYMENT']
  jobs:
  - job: Execute_Deployment_Job
    steps:
    - template: configure_azureml_agent.yml
    - template: execute_python_code.yml
      parameters:
        step_name: "provision azureml online endpoint"
        script_parameter: |
          python -m mlops.common.deployment.provision_batch_endpoint \
            --run_id ${{ parameters.RUN_ID }} \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}

    - template: execute_python_code.yml
      parameters:
        step_name: "provision azureml deployment"
        script_parameter: |
          python -m mlops.common.deployment.provision_batch_deployment \
            --run_id ${{ parameters.RUN_ID }} \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}

    - template: execute_python_code.yml
      parameters:
        step_name: "test azureml batch endpoint"
        script_parameter: |
          python -m mlops.common.deployment.run_test_batch_deployment \
            --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
            --model_type ${{ parameters.MODEL_TYPE }}
