parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
  - stage: build_validation
    displayName: build_validation
    jobs:
      - template: build_validation_pipeline.yml
  - stage: execute_training_job
    displayName: execute_training_job
    dependsOn:
    - build_validation
    jobs:
    - job: Execute_ml_Job_Pipeline
      steps:
      - template: configure_azureml_agent.yml
      - template: execute_python_code.yml
        parameters:
          step_name: "Execute Azure ML pipeline job"
          script_parameter: |
            python -m mlops.${{ parameters.model_type }}.src.mlops_pipeline \
              --build_environment ${{parameters.exec_environment}} \
              --wait_for_completion True \
              --output_file run_id.txt

              readarray arr <"run_id.txt"
              run_name=${arr[0]}
              echo $run_name
              echo "##vso[task.setvariable variable=RUN_NAME;isOutput=true;]$run_name"
            displayName: "Execute Azure ML Pipeline Job"

  - stage: cancel_aml_job
    displayName: Cancel AML Job
    variables: 
      # We are saving the name of Azure ML job submitted in previous step to a variable and it will be used as an input to the AzureML Job Wait task
      azureml_job_name_from_submit_job: $[ dependencies.Execute_ml_Job_Pipeline.outputs['execute_training_job.run_name'] ] 
    condition: canceled()
    jobs:
      - job: CancelAMLPipeline
        displayName: Cancel AML Pipeline if Necessary
        steps:
          - task: AzureCLI@2
            displayName: "Cancel AML Pipeline"
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Pipeline was canceled. Attempting to cancel AML Pipeline..."
                az extension add --name ml
                az ml job cancel --name $(azureml_job_name_from_submit_job) \
                  --resource-group $(RESOURCE_GROUP_NAME) \
                  --workspace-name $(WORKSPACE_NAME)
