parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
  - stage: build_validation
    displayName: build_validation
    jobs:
      - template: build_validation_pipeline.yml
  - stage: execute_training_job
    displayName: execute_training_job
    dependsOn:
    - build_validation
    jobs:
    - job: Execute_ml_Job_Pipeline
      displayName: "Execute Azure ML Pipeline Job"
      steps:
      - template: configure_azureml_agent.yml
      - template: execute_python_code.yml
        parameters:
          step_name: "Execute Azure ML pipeline job"
          script_parameter: |
            python -m mlops.${{ parameters.model_type }}.src.mlops_pipeline \
              --build_environment ${{parameters.exec_environment}} \
              --wait_for_completion True \
              --output_file run_id.txt
      - template: read_run_id.yml
        parameters:
          azure_subscription: $(AZURE_RM_SVC_CONNECTION)
    - job: CancelAzureMLJob
      displayName: Cancel AzureML Job if ADO Pipeline is canceled
      condition: canceled()
      pool: 
        vmImage: ubuntu-latest
      dependsOn: Execute_ml_Job_Pipeline
      variables: 
        azureml_job_name_from_submit_job: $[ dependencies.Execute_ml_Job_Pipeline.outputs['read_run_id.RUN_NAME'] ] 
      steps:
      - script: echo "AzureML Job Name: $(azureml_job_name_from_submit_job)"
      - template: cancel_aml_pipeline.yml
        parameters:
          azure_subscription: $(AZURE_RM_SVC_CONNECTION)
          resource_group_name: $(RESOURCE_GROUP_NAME)
          workspace_name: $(WORKSPACE_NAME)
          run_name: $(azureml_job_name_from_submit_job)
