parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
  - stage: build_validation
    displayName: build_validation
    jobs:
      - template: build_validation_pipeline.yml
  - stage: execute_training_job
    displayName: execute_training_job
    dependsOn:
    - build_validation
    jobs:
    - job: Execute_ml_Job_Pipeline
      steps:
      - template: get_connection_details.yml
      - template: configure_azureml_agent.yml
      - template: execute_mlops_pipeline.yml
        parameters:
          script_parameter: |
            python -m mlops.${{ parameters.model_type }}.src.mlops_pipeline \
              --build_environment ${{parameters.exec_environment}} \
              --wait_for_completion True
