parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
  - stage: build_validation
    displayName: build_validation
    jobs:
      - template: build_validation_pipeline.yml
  - stage: execute_training_job
    displayName: execute_training_job
    dependsOn:
    - build_validation
    jobs:
    - job: Execute_ml_Job_Pipeline
      steps:
      - template: configure_azureml_agent.yml
      - template: execute_python_code.yml
        parameters:
          step_name: "Execute Azure ML pipeline job"
          script_parameter: |
            python -m mlops.${{ parameters.model_type }}.src.mlops_pipeline \
              --build_environment ${{parameters.exec_environment}} \
              --wait_for_completion True \
              --output_file run_id.txt
            displayName: "Execute Azure ML Pipeline Job"
      - task: AzureCLI@2
            displayName: "Cancel AML Pipeline"
            condtion: canceled()
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Pipeline was canceled. Attempting to cancel AML Pipeline..."

                readarray arr <"run_id.txt"
                run_name=${arr[0]}
                echo $run_name

                az extension add --name ml
                az ml job cancel --name $(run_name) \
                  --resource-group $(RESOURCE_GROUP_NAME) \
                  --workspace-name $(WORKSPACE_NAME)
