parameters:
  - name: azure_subscription
    type: string

steps:  
  - task: AzureCLI@2
    displayName: Read Run ID
    name: read_run_id
    inputs:
      azureSubscription: ${{ parameters.azure_subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: $(System.DefaultWorkingDirectory)
      inlineScript: |
        readarray arr <"run_id.txt"
        run_name=${arr[0]}
        echo $run_name
        echo "##vso[task.setvariable variable=RUN_NAME;isOutput=true;]$run_name"

        python -m mlops.common.get_run_metadata \
          --run_id $run_name \
          --output_file_name metadata.txt
        readarray arr <"metadata.txt"
        metadata=${arr[0]}
        echo $metadata
        echo "##vso[task.setvariable variable=RUN_METADATA;isOutput=true;]$metadata"
