

# Azure ML configuration.
aml_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}

environment_configuration:
  env_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04

pipeline_configs:
  pipeline_london_pr: 
    ml_model_config_name: london_taxi
    env_name: pr
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    conda_path: mlops/london_taxi/environment/conda.yml
    display_base_name: london
    aml_env_name: london_env
    experiment_base_name: london
    model_base_name: london
    data_config_path: mlops/london_taxi/configs/data_config.json
  

  deployment_configs:
    batch_deployment_config_london_dev: 
      ml_model_config_name: london_taxi
      env_name: dev
      batch_cluster_name: batchcluster
      endpoint_name: london-taxi-be-005
      deployment_name: london-taxi-bd-005
      cluster_instance_count: 2
      max_concurrency_per_instance: 
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 300
      deployment_base_image_name: 
      deployment_conda_path: model/london_taxi/environment/conda.yml
    
    realtime_deployment_config_london_dev:
      ml_model_config_name: london_taxi
      env_name: dev
      score_file_name: score.py
      test_file_path: model/london_taxi/sample-request.json
      endpoint_name: london-taxi-rte-005
      endpoint_desc: An online endpoint serving an MLflow model for online taxi
      deployment_desc: 
      deployment_name: london-taxi-rtd-005
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image_name: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
      deployment_conda_path: model/london_taxi/environment/conda.yml
      score_dir: model/london_taxi/scoring
      deployment_instance_count: 1
      

      
