name: Custom Object Detection PR Workflow

on:
  pull_request:
    branches:
      - development
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/custom_objectdetection/**'
      - 'model/custom_objectdetection/**'
      - 'src/custom_objectdetection_src/**'
      - 'test/custom_objectdetection/**'
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "custom_objectdetection"
      IS_DOCKER:
        type: boolean
        description: "Is Docker used for build validation?"
        required: true
        default: true
permissions:
  id-token: write
  contents: read    
jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'pr' }}
      model_type: ${{ inputs.model_type || 'custom_objectdetection' }}
      IS_DOCKER: ${{ inputs.IS_DOCKER || true }}
