name: Custom Object Detection CI Workflow

on:
  pull_request:
    branches:
      - development
    paths:
      - mlops/common/**
      - mlops/**
      - mlops/custom_objectdetection/**
      - model/custom_objectdetection/**
      - src/custom_objectdetection_src/**
      - test/custom_objectdetection/**
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "custom_objectdetection"
permissions:
  id-token: write
  contents: read          
jobs:
  run-ci-workflow:
    uses: ./.github/workflows/platform_ci_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'dev' }}
      model_type: ${{ inputs.model_type || 'custom_objectdetection' }}
