name: London Taxi CI Workflow
on:
  push:
    branches:
      - development
    paths:
      - .github/*
      - mlops/common/*
      - mlops/*
      - mlops/london_taxi/*
      - src/*
      - model/london_taxi/*
      - src/london_src/*
      - test/london_taxi/*
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "london_taxi"
      is_batch_deployment:
        type: boolean
        description: "True for batch endpoint and False for real-time endpoint"
        required: true
        default: false

jobs:
  run-ci-workflow:
    uses: ./.github/workflows/platform_ci_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'dev' }}
      model_type: ${{ inputs.model_type || 'london_taxi' }}
      is_batch_deployment: ${{ inputs.is_batch_deployment || false}}
    secrets:
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}