name: CI Workflow
on:
  push:
    branches:
      - development
    paths:
        - .azure-pipelines/*
        - mlops/common/*
        - mlops/nyc_taxi/*
        - src/nyc_src/*
        - model/nyc_taxi/*
        - src/shared/*
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "nyc_taxi"
      is_batch_deployment:
        type: boolean
        description: "True for batch endpoint and False for real-time endpoint"
        required: true
        default: false

jobs:
  run-ci-workflow:
    uses: ./.github/workflows/platform_ci_dev_pipeline.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'dev' }}
      model_type: ${{ inputs.model_type || 'nyc_taxi' }}
      is_batch_deployment: ${{ inputs.is_batch_deployment || false}}
    secrets:
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      aoai_api_key: ${{ secrets.AOAI_API_KEY }}
      aoai_base_endpoint: ${{ secrets.AOAI_BASE_ENDPOINT }}
