# Continuous integration (CI) for nyc taxi model 
name: Nyc Taxi CI Workflow
on:
  push:
    # branches:
    #   - development
    # paths:
    #   - mlops/common/**
    #   - mlops/**
    #   - mlops/nyc_taxi/**
    #   - model/nyc_taxi/**
    #   - src/nyc_src/**
    #   - test/nyc_taxi/**
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "nyc_taxi"

# env: 
#   SUBSCRIPTION_ID: ${{ vars.subscription_id }}
#   RESOURCE_GROUP_NAME: ${{ vars.resource_group_name }}
#   WORKSPACE_NAME: ${{ vars.workspace_name }}
#   ARM_CLIENT_ID: ${{vars.arm_client_id}}
#   ARM_TENANT_ID: ${{vars.arm_tenant_id}}            
#   BUILD_BUILDID: ${{ github.run_id }}
#   BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write
  contents: read          
jobs:
  run-ci-workflow:
    uses: ./.github/workflows/platform_ci_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'dev' }}
      model_type: ${{ inputs.model_type || 'nyc_taxi' }}
