name: Platform PR Dev Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
        default: "nyc_taxi"
    secrets:
      subscription_id:
        description: "the subscription ID hosting the AML instance."
        required: true
      azure_credentials:
        description: "the credentials to use to authenticate with Azure."
        required: true
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
  execute-ml-job-pipeline:
    name: Execute ML Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Retrieve Azure Service Connection
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            export subscriptionId=${{ secrets.SUBSCRIPTION_ID }}
            echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]$subscriptionId"
            tenantId=$(az account show --query tenantId -o tsv)
            echo "##vso[task.setvariable variable=TENANT_ID]$tenantId"
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: Execute ML Job Pipeline step
        run: |
          echo "Current working dir: $(pwd)"
          echo "Executing ML Job Pipeline"
          python -m mlops.${{ inputs.model_type }}.src.mlops_pipeline \
            --build_environment ${{ inputs.exec_environment }} \
            --wait_for_completion True
